# This is an example of the DAITSS configuration file restricted to
# the data necessary to run the viruscheck service.
#
# You must set up your web server to set the environment variable
# DAITSS_CONFIG to point to a configuration file along these lines,
# though typically it will have sections for many services in addition
# to this one.
#
# Please don't use tabs in this file.

defaults:
     temp_directory:             /var/tmp

viruscheck.example.org:
    log_syslog_facility:         LOG_LOCAL0
    clamd:                       false

# defaults:temp_directory
# -----------------------
# Where should temporary files be created? This should be at least
# twice the size of the largest package you plan to ingest, plus
# headroom.  Defaults to system-defined temp directory (typically
# /tmp/)
#
# viruscheck:log_syslog_facility
# -------------------------------
# If set, direct log information to this syslog facility (see
# /etc/syslog.conf), otherwise log to STDERR.
#
# viruscheck:virtual_hostname
# ----------------------------
# What hostname are we running the service under?  This is used as a
# tag in the logs. Defaults to the hostname of the server
#
# viruscheck:clamd
# --------------------------
# Set this to true if clamd is installed and you wish to use it
# instead of invoking the stand-alone clam process for each file.
